# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Soroush Farghadani
#title:
email: sor.fargh@gmail.com
website: Farghadani.me

# Social links
# twitter_username: facespics
github_username:  sfch1999

googlescholar_username: Gv9ET40AAAAJ

# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: soroush-farghadani
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/IMG_4341.jpeg
about_content: | # this will include new lines to allow paragraphs
  **CV: [PDF](https://sfch1999.github.io/files/CV.pdf)**


  I am a Masters student majoring in Computer Science at **University of Toronto**. Currently, I am working as a Research And Development Intern at SOTI - Advanced Aerospace Research.
  My interest is mainly the practical aspects of Artificial Intelligence and Machine Learning. For more details, see my [CV](https://sfch1999.github.io/files/CV.pdf).
# Projects Section
projects_title: Publications

# Experience Section
# experience_title: Experience
# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Science and Technology, some of my other hobbies are:
   - Contemporary Classical Music
   - Mountain Climbing
   - Off-roading

# Footer
footer_show_references: true

# Build settings
remote_theme: sfch1999/sfch1999.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
