# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Soroush Farghadani
title:
email: sor.fargh@gmail.com
# website: shekshaa.github.io

# Social links
# twitter_username: facespics
github_username:  sfch1999
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: soroush-farghadani
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/papyon.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am currently studying the final year of my bachelor’s degree in Computer Engineering at Sharif University of Technology, Iran.
  My research interests include **Deep Learning** in particular, and **Machine Learning** in general, with applications in **Computer Vision**, **Graph Learning**, and **Finance**. 
  I am intended to better understand these methods in a principled manner by investigating 
  their practical implications in real life. 
  Although the recently proposed techniques have demonstrated remarkable performance, 
  significant challenges in terms of Explaining their results remain unresolved. 
  My research goal is to channel such better **theoretical and functional** understandings of 
  these new methods towards better **practical solutions** for real life problems.

# Projects Section
projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Science and Technology, some of my other hobbies are:
   - Contemporary Classical Music
   - Mountain Climbing
   - Off-roading

# Footer
footer_show_references: true

# Build settings
remote_theme: sfch1999/sfch1999.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
